### PR TITLE
Ability to generate the slug from a method

### PR DESCRIPTION
**Pull request by laurentpayot**
Quick PR enabling slug generation from a method. E.g. with methods like <code>fullTitle()</code> who returns <code>title + " by " + author</code>. Feel free to implement a "real" way of defining a method within the slug definition ;)

### CODE REVIEW

**Comment by lukejagodzinski** [comment]
Hey, great idea! I will allow my self to implement it by myself because I need to make some more checks. I will appear soon :)

**Comment by lukejagodzinski** [comment]
I'm thinking about some other approach. Maybe it would be better to allow passing multiple fields to make slug from instead just using method? What do you think? I think that your use case is that you want to create slug from multiple fields.

**Comment by laurentpayot** [comment]
Well slugs are <i>extremely</i> important for SEO. They should be fine tuned, it means we should be able to do whatever we want to generate them. Only a function with full access to the document fields can do that. If the slug is only a concatenation of fields with a separator, how could I add " by " between title and author in the example I gave? And what if I use an array of authors instead of a single author?

**Comment by laurentpayot** [comment]
Also I presume the slug field is needed to allow Iron/Flow Router [Path-to-RegExp](https://github.com/pillarjs/path-to-regexp) routes like <code>'/posts/:_id/:slug'</code>. But I'm going to use direct regular expressions routing which wont need a slug field to be present in the document so it would be great if there could be an option not to add the slug field in the document but to be able to access the <code>generateSlug()</code> function directly, if you see what I mean...

**Comment by lukejagodzinski** [comment]
Ok, your explanation sounds reasonable :) I will do it the way you've proposed :)

**Comment by laurentpayot** [comment]
:+1:

**Comment by laurentpayot** [comment]
Could you add an option to make slugs a <b>transient</b> field so we don't store redundant data in the database?
Also is it possible allow the use of the <code>generateSlug(value, separator)</code> function?

I'm asking a lot, but that would be really great ;)

**Comment by lukejagodzinski** [comment]
I was thinking about such possibility, maybe not exactly making a field transient but give a developer ability to define a field by him/her self. Let's say that you have the `slug` field defined in the class:

``` js
Astro.Class({
  /* ... */
  fields: {
    slug: {
      type: 'string',
      transient: true
    }
  },
  behaviors: ['slug']
});
```

By adding the `slug` behavior the `slug` field with be overridden with:

``` js
{
  slug: {
    type: 'string'
  }
}
```

Behaviors are using the `extend()` method internally. And by default this method is overriding fields, etc. But I think that it shouldn't override a field if it already exists. However, there maybe situations when a developer will want to override it. So it should accept an options object as the second argument.

``` js
Class.extend(schema, {
  override: true // default to true in behaviors false
});
```

If it goes about the `generateSlug()` method I was getting this request already and it's also on my list of features to implement. However, it was more something like forcing slug generation by a developer without any arguments. Why do you need to pass the `value` and `separator` arguments?

**Comment by laurentpayot** [comment]
Class override of the `transient` property would work fine for my use at least.

For instance in my app I need to remove diacritics of a string and other kinds of cleanups before to generate a custom hash ID. That's exactly what  `generateSlug()` does to its `value` argument. It's a quite useful function that I would love to use a bit everywhere.

**Comment by lukejagodzinski** [comment]
The `slug` behavior replaces most of the diacritics with their latin equivalents. However with the `methodName` option you will be able to do something like this:

``` js
Item = Astro.Class({
  /* ... */
  fields: {
    a: 'string',
    b: 'string'
    c: 'number'
  },
  methods: {
    forSlug: function() {
      var value = this.a + ' ' + this.b + ' from ' + this.c;
      // Remove some diacritics here...
      return value;
    }
  },
  behaviors: {
    slug: {
      fieldName: null,
      methodName: 'forSlug'
    }
  }
});
```

Now you will be able to force the slug generation:

``` js
var item = new Item();
item.set({
  a: 'ąść',
  b: 'łóń',
  c: 123
});
item.generateSlug();
item.slug; // "asc-lon-from-123"
```

I think it's flexible enough. You can do almost every possible combination. In fact I've already implemented it and it will appear soon as a new version of the `slug` behavior (1.1.0).

**Comment by lukejagodzinski** [comment]
And I've didn't even remember but I've already implemented a possibility to make a field transient :D.
You can just define a field in a class schema and it will override the one from a behavior.

**Comment by laurentpayot** [comment]
Do you mean we will have to write our own diacritics removal inside our custom `forSlug()` method? That would be a bit of a step back...

Ok I'll try to override the transient property later tonight. Thanks!

**Comment by lukejagodzinski** [comment]
No no I mean that the `slug` behavior does it automatically but if you want to get into the process and do something more then you can do it in the custom function. I will update the example app to show how will it work.

**Comment by laurentpayot** [comment]
Sounds great then :+1:

**Comment by laurentpayot** [comment]
Class override is working :) But now that I look at it it seems like a bad practice to have two different places in the schema (in the field and in the behavior definitions) to set the properties of the slug. Would it be possible to simply have a `transient` option in the slug <b>behavior</b> parameters so everything about the slug is at one place?

**Comment by laurentpayot** [comment]
Oops no after further tests if `i = Items.findOne()` then `i.slug`is null when we override `transient: true` in the `Items` slug field definition.

**Comment by lukejagodzinski** [comment]
Yes it's null because you have to wait for an update that will allow you to call the `generateSlug()` method after document creation in the `afterInit` event. I don't want to add such options like `transient` to the behavior because it would be rarely used. Most people want to save a slug in the database. Slug is mostly used in a routing.

**Comment by laurentpayot** [comment]
Ok then it's not a big deal. By the way transient fields generated "on the fly" in the `afterInit` event are working well with Iron router  path-to-regexp syntax. I'm using one for routing i18n (translated categories).

**Comment by lukejagodzinski** [comment]
Could you show me some example code? I'm curious how it works without storing slug in a collection.

**Comment by laurentpayot** [comment]
Sure, here is some (simplified) code in <i>CoffeeScript</i>, hope you dont mind...

``` coffeescript
# collections.coffee

@Items = new Mongo.Collection('items')
@Item = Astro.Class(
    name: 'item'
    collection: Items
    typeField: 'type'
    fields:
        'title':
            type: 'string'
            default: ""
        'i18nTypePath':
            type: 'string'
            transient: true
    behaviors:
        slug:
            fieldName: 'title'
            slugFieldName: 'slug'
            canUpdate: true
            separator: '-'
    events:
        afterInit: (e) ->
            if Meteor.isClient
                # "__" is the translation function
                # 'book_type_path' english translation is "books"
                # 'book_type_path' french translation is "livres"
                @set('i18nTypePath', __(@type + '_type_path'))
)

@Book = Item.inherit(
    name: "book"
    fields:
        'wordCount':
            type: 'number'
            default: 0
)

b = new Book()
b.set('title', "Foo Bar")
b.save() # let's say _id is "wxyz"
```

``` coffeescript
# router.coffee

Router.route('/:i18nTypePath/:_id/:slug',
    name: 'itemDetails'
    data: -> Items.findOne({_id: @params._id})
    action: -> @render('itemDetails')
)
```

Then in a template with the previously saved book `b` as the context if I use `{{pathFor 'itemDetails'}}` with a French browser I will get `(/fr)/livres/wxyz/foo-bar`. With an English browser I will get  `(/en)/books/wxyz/foo-bar`.

That's why I needed a "transient-like" slug that would also be generated "on the fly" depending of the client language. With a slug saved in the database I have to use a single slug for all languages (bye-bye "by" between title and author as for my previous example).

**Comment by lukejagodzinski** [comment]
Oh I see, so you're just querying a document by its ID not its slug and you use slug to display a language specific data. I just thought that you're doing it in some magical way :-). Ok so going back to discussion about improvements. They will appear soon as they are already implemented. I just want to make a bigger update instead many small.

**Comment by laurentpayot** [comment]
I'm now using the new slug version (and overriding the transient property). It's working fine. Thank you so much @jagi for all the great work you do! :)

**Comment by lukejagodzinski** [comment]
Ok good to hear :) Enjoy :)

**Pull request closed without merging**
